### ISSUE TITLE
rp5adfix.js doesn't work

### ISSUE THREAD

**Issue by fliker09** [StSav012/adblockrules#3]
![image](https://user-images.githubusercontent.com/18057950/55995002-05a7c980-5cbc-11e9-9781-61b13ce41d6a.png)
Using Greasemonkey + Firefox. If any additional info required just let me know!

**Comment by StSav012** [comment]
I could not repeat it for the desktop version of the site but the mobile version has given me a hint. Try https://github.com/StSav012/adblockrules/commit/f986d630fd2c5b8eea759fdffd44e870eef7462c.

If the result is the same, please tell me the browser and the add-on versions, at least.

And please verify that the script runs with the URL you visit. I might have just forgotten a mask in the `@match` metadata of the script. Apparently, I have forgotten `rp5.by` and `rp5.co.uk` indeed. Moreover, there are `расписаниепогоды.рф` and `рп5.рф` but they redirect to `rp5.ru`.

**Comment by fliker09** [comment]
Firefox 66.0.2 / Greasemonkey 4.7
Tested on mobile version - does the trick. But desktop version is still affected by anti-adblocker.
Tested on rp5.ru

**Comment by StSav012** [comment]
All right, I'm getting to the bottom. It appears that they have found a way to fix the adblocker issue in [RU AdList](https://forums.lanik.us/viewforum.php?f=102). That's why I have been having trouble repeating the issue.

Anyway, after https://github.com/StSav012/adblockrules/commit/aceeadc1f80f585361a728bc38d390c772c854ad it seems to work fine both with and without the latest RU AdList changes enabled.

**Comment by fliker09** [comment]
Yep, it works now! Thanks!
